"""Add Review Model

Revision ID: f14b0b0fcea4
Revises: dbbae2c2cf89
Create Date: 2023-12-09 21:32:53.586987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f14b0b0fcea4'
down_revision = 'dbbae2c2cf89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
